### ISSUE TITLE
Missing FAQ or hints to make extension work

### ISSUE THREAD

**Issue by p-Enzi** [move-elevator/me_shortlink#1]
Your instruction How to use
5. www.your-domain.com/yourshortlink
lacks some basic informations about the conzent of the .htaccess
you are using.
A call to a non-existent subdir like /yourshortlink will not work on any webspace or server without 
settings in the htaccess of the webspace.

**Comment by janmaennig** [comment]
Hello p-Enzi,

thanks for your feedback. You can use the default .htaccess file from TYPO3 (https://github.com/TYPO3/TYPO3.CMS/blob/master/_.htaccess). There are no specifications required.

Best regards
Jan
