### ISSUE TITLE
Please give infos to the "Shortlink-Domain" 

### ISSUE THREAD

**Issue by p-Enzi** [move-elevator/me_shortlink#2]
What is this element Shortlink-Domain used for?
Please give some hints how to use it.

**Comment by janmaennig** [comment]
Hello p-Enzi again!

With the element "Shortlink-Domain" you have the possibility to differentiate shortlinks in multi domain projects. We will extend the documentation soon. 

The sysfolder, you store the short link in, should contain at least one short link domain.

Best regards
Jan
